# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: localhost
      POSTGRES_PORT: 5432
      STREAMUS_TEST_DATABASE_NAME: streamustest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      STREAMUS_TEST_RESOURCE_PATH: /media/
      STREAMUS_JWT_SECRET: 1234567890-qwertzuiop-asdfghjkl-yxcvbnm-1234567890-qwertzuiop-asdfghjkl-yxcvbnm-1234567890-qwertzuiop-asdfghjkl-yxcvbnm-1234567890-qwertzuiop-asdfghjkl-yxcvbnm-1234567890-qwertzuiop-asdfghjkl-yxcvbnm-1234567890-qwertzuiop-asdfghjkl-yxcvbnm
    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      # You may pin to the exact commit or the version.
      # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 13
        # POSTGRES_DB - name for the default database that is created
        postgresql db: ${STREAMUS_TEST_DATABASE_NAME}
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: ${POSTGRES_USER}
        # POSTGRES_PASSWORD - superuser password
        postgresql password: ${POSTGRES_PASSWORD}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
